AllCops:
  Exclude:
    - "spec/spec_helper.rb"
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - "spec/*"
Layout/LineLength:
  Exclude:
    - "spec/*"
Metrics/ClassLength:
  Exclude:
    - "lib/board.rb"
Metrics/ModuleLength:
  Exclude:
    - "lib/display.rb"